package com.scanapk.app.ui.theme

import androidx.compose.ui.graphics.Color

val Surface = Color(0xFFF8F9FA)
val SurfaceDim = Color(0xFFD9DADB)
val SurfaceBright = Color(0xFFF8F9FA)
val SurfaceContainerLowest = Color(0xFFFFFFFF)
val SurfaceContainerLow = Color(0xFFF3F4F5)
val SurfaceContainer = Color(0xFFEDEEEF)
val SurfaceContainerHigh = Color(0xFFE7E8E9)
val SurfaceContainerHighest = Color(0xFFE1E3E4)
val OnSurface = Color(0xFF191C1D)
val OnSurfaceVariant = Color(0xFF414754)
val InverseSurface = Color(0xFF2E3132)
val InverseOnSurface = Color(0xFFF0F1F2)
val Outline = Color(0xFF727785)
val OutlineVariant = Color(0xFFC1C6D6)
val SurfaceTint = Color(0xFF005BC0)

val Primary = Color(0xFF005BBF)
val OnPrimary = Color(0xFFFFFFFF)
val PrimaryContainer = Color(0xFF1A73E8)
val OnPrimaryContainer = Color(0xFFFFFFFF)
val InversePrimary = Color(0xFFADC7FF)
val PrimaryFixed = Color(0xFFD8E2FF)
val PrimaryFixedDim = Color(0xFFADC7FF)
val OnPrimaryFixed = Color(0xFF001A41)
val OnPrimaryFixedVariant = Color(0xFF004493)

val Secondary = Color(0xFF5B5F64)
val OnSecondary = Color(0xFFFFFFFF)
val SecondaryContainer = Color(0xFFDDE0E6)
val OnSecondaryContainer = Color(0xFF5F6368)
val SecondaryFixed = Color(0xFFDFE3E8)
val SecondaryFixedDim = Color(0xFFC3C7CC)
val OnSecondaryFixed = Color(0xFF181C20)
val OnSecondaryFixedVariant = Color(0xFF43474C)

val Tertiary = Color(0xFF9E4300)
val OnTertiary = Color(0xFFFFFFFF)
val TertiaryContainer = Color(0xFFC55500)
val OnTertiaryContainer = Color(0xFF0E0200)
val TertiaryFixed = Color(0xFFFDBCB)
val TertiaryFixedDim = Color(0xFFFFB691)
val OnTertiaryFixed = Color(0xFF341100)
val OnTertiaryFixedVariant = Color(0xFF783100)

val Error = Color(0xFFBA1A1A)
val OnError = Color(0xFFFFFFFF)
val ErrorContainer = Color(0xFFFFDAD6)
val OnErrorContainer = Color(0xFF93000A)

val Background = Color(0xFFF8F9FA)
val OnBackground = Color(0xFF191C1D)
val SurfaceVariant = Color(0xFFE1E3E4)

val DarkSurface = Color(0xFF1A1C1E)
val DarkOnSurface = Color(0xFFE1E3E4)
val DarkOnSurfaceVariant = Color(0xFFC1C6D6)
val DarkSurfaceVariant = Color(0xFF414754)
val DarkBackground = Color(0xFF1A1C1E)
val DarkOnBackground = Color(0xFFE1E3E4)

val SeveritySafe = Color(0xFF34A853)
val SeveritySafeBg = Color(0xFFE6F4EA)
val SeverityLow = Color(0xFFFBBC04)
val SeverityLowBg = Color(0xFFFEF7E0)
val SeverityMedium = Color(0xFFFA7B17)
val SeverityMediumBg = Color(0xFFFEEFD9)
val SeverityHigh = Color(0xFFEA4335)
val SeverityHighBg = Color(0xFFFCE8E6)
val SeverityCritical = Color(0xFF8B0000)
val SeverityCriticalBg = Color(0xFFF2DEDE)
